"""Contenu de la maquette de parcours. Textes de DÉMONSTRATION (écrits pour tester la fluidité, non vérifiés) ; trois niveaux comme le curseur de l'appli."""

TITLE = "De la lumière à la couleur"
SUBTITLE = "Monet, puis Gauguin — un parcours pour amateur de zooms profonds et de textes qui expliquent"


def T(a, b, c):
    return {"1": a, "2": b, "3": c}


SEQS = {
    "main": {
        "label": "Parcours principal",
        "steps": [
            {"type": "t", "work": "parasol", "title": "Ouverture",
             "text": T("Deux peintres, deux façons de regarder.",
                       "En vingt ans, la peinture passe de la lumière qui vibre à la couleur posée à plat. Ce parcours suit ce glissement, de Monet à Gauguin, en s'arrêtant sur ce que l'œil ne voit pas de loin.",
                       "En vingt ans, la peinture passe de la lumière qui vibre à la couleur posée à plat. Monet cherche à saisir un instant ; Gauguin veut peindre ce qui ne se voit pas. Ce parcours alterne les zooms au cœur de la matière et les clés pour comprendre ce qu'on regarde. Vous pouvez à tout moment ouvrir un sous-parcours, puis revenir ici."),
             "branches": [{"seq": "manet", "label": "Avant Monet : Manet", "hint": "3 étapes · la vie moderne"}]},
            {"type": "g", "work": "parasol", "title": "La Femme à l'ombrelle",
             "stops": [
                 {"crop": None, "cap": T("Monet, 1875. Camille et leur fils Jean, sur une colline d'Argenteuil.",
                                         "Le tableau est peint vite, en plein air. On le regarde d'en bas : Camille se détache sur le ciel comme une silhouette prise dans le vent.",
                                         "Le tableau est peint vite, en plein air, probablement en une ou deux séances. Le point de vue en contre-plongée découpe Camille sur le ciel ; l'ombrelle, le voile et l'herbe sont pris dans le même mouvement d'air. Rien n'est fini au sens académique : c'est ce qui choquait, et ce qui fascine.")},
                 {"crop": "z1", "cap": T("Le visage est à peine dessiné.",
                                         "De près, le visage n'a presque pas de traits : quelques touches suffisent, mangées par le voile et la lumière qui vient de derrière.",
                                         "De près, le visage n'a presque pas de traits : quelques touches suffisent, mangées par le voile et par le contre-jour. Monet ne peint pas une personne mais un effet : la manière dont la lumière traverse le tissu et efface les contours. C'est un choix, pas une maladresse : il sait dessiner un visage, il refuse ici de le faire.")},
                 {"crop": "z2", "cap": T("Le voile : trois couleurs, posées sans mélange.",
                                         "Au plus près, le blanc du voile est fait de bleus, de verts et de roses posés côte à côte. C'est l'œil qui les mélange à distance.",
                                         "Au plus près, le blanc du voile n'est jamais blanc : bleus, verts, roses et ocres sont posés côte à côte, souvent sans être mélangés sur la palette. À distance, l'œil fond ces touches en une lumière vibrante. C'est le principe que les néo-impressionnistes systématiseront dix ans plus tard avec le point.")},
             ]},
            {"type": "h", "work": "parasol", "bg": "z1", "title": "Peindre dehors",
             "text": T("Le tube de peinture a rendu le plein air possible.",
                       "Avant 1840, la peinture se préparait à l'atelier et se transportait mal. Le tube d'étain, souple et refermable, permet de peindre dehors toute une journée. Les impressionnistes en font une méthode : peindre sur le motif, vite, avant que la lumière change.",
                       "Avant 1840, la peinture se préparait à l'atelier, dans des vessies de porc fragiles. Le tube d'étain, souple et refermable, change tout : on peut emporter vingt couleurs dans une boîte et peindre dehors toute une journée. Renoir dira plus tard que sans les tubes, il n'y aurait pas eu d'impressionnisme. Peindre sur le motif impose la vitesse : la touche devient visible, rapide, et c'est elle qui porte l'émotion.")},
            {"type": "g", "work": "rouen", "title": "La Cathédrale de Rouen, plein soleil",
             "stops": [
                 {"crop": None, "cap": T("Monet, 1894. Une des trente vues de la même façade.",
                                         "Monet loue une chambre face à la cathédrale et peint la façade à toutes les heures. Ici, le plein soleil la transforme en paroi de lumière.",
                                         "Monet loue une chambre face à la cathédrale et peint la même façade à toutes les heures, sur plus de trente toiles qu'il reprend ensuite à l'atelier. Le sujet n'est plus la cathédrale mais l'heure : le plein soleil la change en une paroi de lumière dorée, presque sans profondeur.")},
                 {"crop": "z1", "cap": T("Le portail se dissout dans la lumière.",
                                         "Le grand portail n'a plus de lignes nettes : l'ombre est bleue, la pierre au soleil est orange et crème.",
                                         "Le grand portail n'a plus de lignes nettes. L'ombre n'est pas grise mais bleue et violette ; la pierre au soleil est orange, crème, rose. Monet peint des couleurs complémentaires côte à côte pour faire vibrer le contraste, plutôt que d'assombrir pour creuser le relief.")},
                 {"crop": "z2", "cap": T("La peinture devient presque sculpture.",
                                         "De très près, la matière est épaisse, croûteuse, comme la pierre qu'elle représente.",
                                         "De très près, la matière est épaisse et croûteuse, posée en couches successives au fil des séances. La surface de la toile imite la rugosité de la pierre : la peinture ne représente plus seulement la façade, elle en reprend la texture. Les visiteurs de 1895 parlaient de « mortier ».")},
             ]},
            {"type": "h", "work": "rouen", "bg": "z1", "title": "Les séries : peindre le temps",
             "text": T("Peindre le même motif pour peindre l'heure qui passe.",
                       "Meules, peupliers, cathédrale, Parlement de Londres : Monet multiplie les séries. Exposées ensemble, les toiles montrent le temps qui passe sur un même lieu.",
                       "Meules, peupliers, cathédrale, Parlement de Londres, nymphéas : à partir de 1890, Monet travaille par séries. Il installe plusieurs toiles côte à côte et passe de l'une à l'autre quand la lumière change. Exposées ensemble chez Durand-Ruel, ces séries font du temps lui-même le sujet de l'exposition. Elles se vendent très bien : la série est aussi une réussite commerciale."),
             "branches": [{"seq": "londres", "label": "Londres dans la brume", "hint": "3 étapes · zoom profond"}]},
            {"type": "t", "work": "haystacks", "title": "Au même moment, en Bretagne",
             "text": T("Pendant que Monet peint ses meules, Gauguin peint les siennes.",
                       "À Pont-Aven puis au Pouldu, un ancien agent de change devenu peintre cherche autre chose que la lumière : une couleur qui ait du sens.",
                       "À Pont-Aven puis au Pouldu, Paul Gauguin, ancien agent de change devenu peintre à plein temps, vit de peu et entraîne de jeunes artistes. Il a exposé avec les impressionnistes, mais il s'en éloigne : il ne veut plus copier ce que l'œil reçoit, il veut simplifier, cerner, accentuer.")},
            {"type": "g", "work": "haystacks", "title": "Meules en Bretagne",
             "stops": [
                 {"crop": None, "cap": T("Gauguin, 1890. Le même motif que Monet, un tout autre résultat.",
                                         "Les meules sont des blocs, les champs des bandes de couleur. La profondeur s'aplatit comme dans une tapisserie.",
                                         "Les meules ne vibrent pas : ce sont des blocs aux contours nets, posés sur des champs traités en bandes de couleur. La profondeur s'aplatit comme dans une tapisserie ou un vitrail. Gauguin garde le motif rural cher aux impressionnistes, mais il le recompose.")},
                 {"crop": "z1", "cap": T("Une paysanne et ses vaches, au premier plan.",
                                         "Les vaches sont découpées par des taches noires et blanches presque abstraites ; la paysanne est réduite à une silhouette.",
                                         "Les vaches sont découpées en taches noires et blanches presque abstraites ; la paysanne est réduite à une silhouette verticale. Les couleurs orange et rouge du premier plan ne cherchent pas la vraisemblance : elles équilibrent la composition.")},
                 {"crop": "z2", "cap": T("La coiffe blanche, un trait de Bretagne.",
                                         "La coiffe est un simple aplat blanc cerné : un signe plus qu'une description.",
                                         "La coiffe est un simple aplat blanc, cerné d'un trait sombre : un signe plus qu'une description. Gauguin cherche en Bretagne un monde « primitif » et religieux, qu'il idéalise en partie : les paysans de Pont-Aven accueillaient aussi beaucoup de touristes et de peintres.")},
             ]},
            {"type": "h", "work": "haystacks", "bg": "z1", "title": "Le synthétisme",
             "text": T("Simplifier pour dire plus.",
                       "Avec Émile Bernard, Gauguin cerne les formes d'un trait sombre et pose la couleur en aplats. On appelle cela le cloisonnisme, en référence aux émaux et aux vitraux.",
                       "Avec Émile Bernard, Gauguin cerne les formes d'un trait sombre et pose la couleur en aplats, comme dans les émaux cloisonnés ou les vitraux : c'est le cloisonnisme. Le synthétisme va plus loin : peindre de mémoire plutôt que sur le motif, garder l'essentiel de la forme, du sentiment et de l'idée. Les estampes japonaises, que tous ces peintres collectionnent, montrent la voie : contours nets, couleurs plates, cadrages audacieux."),
             "branches": [{"seq": "japon", "label": "Le Japon, modèle commun", "hint": "2 étapes · Monet et Gauguin"},
                          {"seq": "portrait", "label": "Gauguin face à lui-même", "hint": "2 étapes · zoom très profond"}]},
            {"type": "t", "work": "fatata", "title": "1891 : départ pour Tahiti",
             "text": T("Gauguin quitte l'Europe pour Tahiti.",
                       "Il espère y trouver un paradis intact et une vie bon marché. Il trouve une colonie, mais il peindra le paradis qu'il cherchait.",
                       "Il espère y trouver un paradis intact, loin de « la civilisation », et une vie bon marché. Il découvre une colonie française déjà transformée par les missions et l'administration. Il peindra pourtant le monde qu'il espérait : ses toiles tahitiennes mêlent l'observation, les récits anciens et une large part d'invention.")},
            {"type": "g", "work": "fatata", "title": "Fatata te Miti (Au bord de la mer)",
             "stops": [
                 {"crop": None, "cap": T("Gauguin, 1892. Deux femmes s'apprêtent à plonger.",
                                         "Le tronc d'arbre coupe le tableau en diagonale ; le sable rose et l'eau émeraude sont posés en grandes zones.",
                                         "Le tronc d'arbre coupe le tableau en diagonale, comme dans une estampe japonaise. Le sable rose, l'eau émeraude et le sol violet sont posés en grandes zones qui ne cherchent pas la vraisemblance. Le titre tahitien, écrit en bas, fait partie de l'image.")},
                 {"crop": "z1", "cap": T("Une silhouette de dos, prête à entrer dans l'eau.",
                                         "Le corps est modelé simplement, entre ombre et lumière, sans détail superflu.",
                                         "Le corps est modelé simplement, par un dégradé brun doré et un contour sombre. Gauguin s'inspire de frises antiques et de photographies qu'il collectionne : la pose est presque une citation.")},
                 {"crop": "z2", "cap": T("Les arabesques jaunes sur le sable rose.",
                                         "Au premier plan, des formes jaunes et orange dansent sur le rose : ce sont des algues, ou de purs ornements.",
                                         "Au premier plan, des formes jaunes et orange dansent sur le rose. Ce sont peut-être des algues ou des feuilles, mais elles fonctionnent d'abord comme des ornements, proches des motifs décoratifs que Gauguin sculpte sur bois à la même époque.")},
             ]},
            {"type": "h", "work": "fatata", "bg": "z2", "title": "La couleur qui ne décrit plus",
             "text": T("Chez Gauguin, la couleur exprime, elle ne copie pas.",
                       "Un sable rose ou un chien rouge ne sont pas des erreurs : la couleur porte une émotion, une musique. Cette liberté ouvrira la voie aux Nabis et aux Fauves.",
                       "Un sable rose ou un chien rouge ne sont pas des erreurs : Gauguin compare la couleur à la musique, qui émeut sans imiter. Cette liberté, transmise par l'intermédiaire de Paul Sérusier et de son petit tableau « Le Talisman », ouvre la voie aux Nabis, puis aux Fauves de Matisse et Derain une quinzaine d'années plus tard.")},
            {"type": "g", "work": "bathers", "title": "Les Baigneuses",
             "stops": [
                 {"crop": None, "cap": T("Gauguin, 1897. Une frise de figures dans un paysage-décor.",
                                         "Les baigneuses se répartissent comme sur un bas-relief ; le paysage est une tapisserie de couleurs.",
                                         "Les baigneuses se répartissent comme les figures d'un bas-relief, sans action précise. Le paysage est une tapisserie de couleurs où l'eau, les fleurs et la terre ont la même importance. L'année 1897 est terrible pour Gauguin, malade et endetté ; ses tableaux restent pourtant sereins.")},
                 {"crop": "z1", "cap": T("Deux femmes au bord de l'eau.",
                                         "Les visages sont graves, tournés vers l'intérieur : Gauguin peint un état plus qu'une scène.",
                                         "Les visages sont graves, tournés vers l'intérieur. Gauguin peint un état, une sorte de méditation, plus qu'une scène de baignade. Les pagnes et les fleurs donnent les seules couleurs franches.")},
                 {"crop": "z2", "cap": T("Les fleurs dans les cheveux.",
                                         "De très près, la fleur est faite de quelques touches blanches et roses sur une chevelure presque noire.",
                                         "De très près, la fleur est faite de quelques touches blanches et roses sur une chevelure presque noire, et l'on devine la trame de la toile grossière que Gauguin utilisait faute d'argent. La texture du support participe à l'aspect mat, presque de fresque, de ses tableaux tahitiens.")},
             ]},
            {"type": "end", "work": "bathers", "title": "Fin du parcours",
             "text": T("De la lumière qui vibre à la couleur qui parle.",
                       "Monet a dissous les formes dans la lumière ; Gauguin les a recomposées en aplats de couleur. Deux chemins qui mènent, chacun, à la peinture du XXe siècle.",
                       "Monet a dissous les formes dans la lumière jusqu'à l'abstraction des Nymphéas ; Gauguin les a recomposées en aplats de couleur chargés de sens. Le premier ouvre la voie aux peintres de la matière et du geste, le second aux Nabis, aux Fauves et à l'expressionnisme."),
             "branches": [{"seq": "manet", "label": "Avant Monet : Manet", "hint": "Manet"},
                          {"seq": "londres", "label": "Londres dans la brume", "hint": "Monet"},
                          {"seq": "japon", "label": "Le Japon, modèle commun", "hint": "Monet et Gauguin"},
                          {"seq": "portrait", "label": "Gauguin face à lui-même", "hint": "Gauguin"}]},
        ],
    },
    "londres": {
        "label": "Sous-parcours : Londres dans la brume",
        "steps": [
            {"type": "g", "work": "parliament", "title": "Le Parlement de Londres, coucher de soleil",
             "stops": [
                 {"crop": None, "cap": T("Monet, 1903. Le Parlement noyé dans la brume rose.",
                                         "Depuis l'hôpital Saint-Thomas, de l'autre côté de la Tamise, Monet peint le Parlement à contre-jour, pris dans la brume.",
                                         "Depuis une terrasse de l'hôpital Saint-Thomas, de l'autre côté de la Tamise, Monet peint le Parlement à contre-jour. La brume, chargée de la fumée des usines, colore la lumière : Monet adorait le brouillard londonien, qu'il disait être ce qui donne à Londres son ampleur.")},
                 {"crop": "z1", "cap": T("Le soleil se brise sur l'eau.",
                                         "Les reflets sont des virgules orange et roses sur un fond bleu-vert.",
                                         "Les reflets sont des virgules orange et roses posées sur un fond bleu-vert. Monet travaille souvent sur plusieurs toiles à la fois, changeant de toile dès que la lumière change, parfois toutes les quinze minutes.")},
                 {"crop": "z2", "cap": T("Une barque, presque effacée.",
                                         "Une barque sombre, quelques touches à peine, donne l'échelle à tout le tableau.",
                                         "Une barque sombre, quelques touches à peine, donne l'échelle à tout le tableau et un point d'arrêt pour l'œil. C'est le seul signe humain de la scène.")},
             ]},
            {"type": "h", "work": "parliament", "bg": "z1", "title": "Le brouillard, un sujet",
             "text": T("Monet a peint près d'une centaine de vues de Londres.",
                       "Entre 1899 et 1904, il séjourne plusieurs fois à Londres et peint trois séries : le Parlement, Waterloo Bridge et Charing Cross Bridge.",
                       "Entre 1899 et 1904, il séjourne plusieurs fois à Londres et peint trois séries : le Parlement, Waterloo Bridge et Charing Cross Bridge. Il termine beaucoup de toiles à Giverny, de mémoire, en les harmonisant entre elles, ce qui lui vaut des critiques : peindre « sur le motif » était devenu une légende plus qu'une règle.")},
            {"type": "back", "work": "parliament", "title": "Retour au parcours principal",
             "text": T("On reprend là où vous en étiez.", "On reprend là où vous en étiez, juste après les séries de Monet.", "On reprend là où vous en étiez, juste après les séries de Monet. Ce sous-parcours compte dans ce que l'appli apprend : vous avez choisi d'approfondir la lumière.")},
        ],
    },
    "japon": {
        "label": "Sous-parcours : le Japon, modèle commun",
        "steps": [
            {"type": "g", "work": "footbridge", "title": "Le Pont japonais",
             "stops": [
                 {"crop": None, "cap": T("Monet, 1899. Le pont de son jardin de Giverny.",
                                         "Monet a fait construire ce pont en bois peint en vert, inspiré des estampes japonaises qu'il collectionnait.",
                                         "Monet a fait construire ce pont en bois au-dessus de son bassin, inspiré des estampes japonaises qu'il collectionnait par centaines et qui couvrent encore les murs de sa maison. Le cadrage serré, sans ciel ni berges, ferme l'espace comme une estampe.")},
                 {"crop": "z1", "cap": T("L'arche du pont, presque un idéogramme.",
                                         "La courbe verte se détache sur un mur de feuillage : c'est elle qui structure la toile.",
                                         "La courbe verte se détache sur un mur de feuillage : un seul signe graphique structure toute la toile, à la manière d'une calligraphie.")},
                 {"crop": "z2", "cap": T("Un nymphéa : une touche rose et blanche.",
                                         "De près, chaque fleur est une petite boule de peinture posée d'un geste.",
                                         "De près, chaque fleur est une petite boule de peinture posée d'un seul geste, sur des reflets horizontaux. Les Nymphéas des vingt-cinq dernières années de Monet sont déjà là, en germe.")},
             ]},
            {"type": "h", "work": "footbridge", "bg": "z1", "title": "Le japonisme",
             "text": T("Les estampes japonaises ont nourri Monet comme Gauguin.",
                       "Après 1860, les estampes japonaises arrivent en masse à Paris. Monet y trouve des cadrages, Gauguin des aplats cernés.",
                       "Après l'ouverture du Japon au commerce, dans les années 1860, les estampes ukiyo-e arrivent en masse à Paris, parfois comme papier d'emballage. Monet y trouve des cadrages audacieux et l'idée de la série (les « Vues du mont Fuji » d'Hokusai) ; Gauguin et Bernard y trouvent les aplats cernés et l'absence d'ombre. Le même modèle produit deux peintures opposées.")},
            {"type": "back", "work": "footbridge", "title": "Retour au parcours principal",
             "text": T("On reprend avec Gauguin.", "On reprend avec Gauguin, au moment où il part pour Tahiti.", "On reprend avec Gauguin, au moment où il part pour Tahiti. Ce détour compte dans ce que l'appli apprend : vous reliez les artistes entre eux.")},
        ],
    },
    "portrait": {
        "label": "Sous-parcours : Gauguin face à lui-même",
        "steps": [
            {"type": "g", "work": "selfportrait", "title": "Autoportrait",
             "stops": [
                 {"crop": None, "cap": T("Gauguin, 1889. Une auréole, une pomme, un serpent.",
                                         "Gauguin se peint en saint ironique : auréole au-dessus de la tête, serpent entre les doigts, pommes de la tentation.",
                                         "Gauguin se peint en personnage double : saint et tentateur. Auréole au-dessus de la tête, serpent entre les doigts, pommes de la tentation, le tout sur des fonds rouge et jaune purs. Peint sur une porte d'armoire de l'auberge du Pouldu, le panneau tient du blason autant que du portrait.")},
                 {"crop": "z1", "cap": T("Le visage, cerné comme un émail.",
                                         "Les contours sont nets, les ombres vertes : le visage devient un masque.",
                                         "Les contours sont nets et les ombres vertes : le visage devient un masque, entre caricature et icône. On retrouve ici le cloisonnisme du sous-parcours précédent appliqué à soi-même.")},
                 {"crop": "z2", "cap": T("L'œil mi-clos, qui nous évite.",
                                         "Le regard glisse de côté, la paupière lourde : Gauguin se montre à la fois fier et méfiant.",
                                         "Le regard glisse de côté sous une paupière lourde. De très près, l'œil tient en trois couleurs et un trait : la simplification la plus extrême au service de l'expression.")},
             ]},
            {"type": "back", "work": "selfportrait", "title": "Retour au parcours principal",
             "text": T("On reprend avec Tahiti.", "On reprend au moment du départ pour Tahiti.", "On reprend au moment du départ pour Tahiti. Ce détour compte dans ce que l'appli apprend : vous aimez les zooms très profonds sur les visages.")},
        ],
    },
    "manet": {
        "label": "Sous-parcours : avant Monet, Manet",
        "steps": [
            {"type": "g", "work": "railway", "title": "Le Chemin de fer",
             "stops": [
                 {"crop": None, "cap": T("Manet, 1873. Une femme et une fillette devant la gare Saint-Lazare.",
                                         "Le train n'est qu'un nuage de vapeur derrière la grille. Manet peint la ville moderne sans la montrer, à travers deux personnages qui s'ignorent.",
                                         "Le train n'est qu'un nuage de vapeur blanche derrière une grille noire qui barre tout le tableau. Manet peint la ville moderne sans la montrer : la femme lève les yeux de son livre vers nous, la fillette nous tourne le dos pour regarder les voies. Au Salon de 1874, le public n'y comprend rien et les caricaturistes s'en moquent.")},
                 {"crop": "z1", "cap": T("Le regard qui nous fixe.",
                                         "Victorine Meurent, son modèle favori, nous regarde droit dans les yeux, comme dans l'Olympia dix ans plus tôt.",
                                         "C'est Victorine Meurent, son modèle favori, déjà l'Olympia et la femme du Déjeuner sur l'herbe. Son regard direct, sans sourire, met le spectateur mal à l'aise : il n'est plus un observateur invisible mais un passant surpris.")},
                 {"crop": "z2", "cap": T("Un chiot endormi sur ses genoux.",
                                         "Le petit chien est peint en quelques coups de pinceau larges, sans contour : la touche de Manet annonce déjà celle des impressionnistes.",
                                         "Le petit chien est peint en quelques coups de pinceau larges et rapides, sans contour dessiné. Manet travaille par grandes masses claires et sombres, sans demi-teintes : c'est cette franchise de la touche que les jeunes impressionnistes admirent chez lui.")},
             ]},
            {"type": "h", "work": "railway", "bg": "z1", "title": "Le peintre de la vie moderne",
             "text": T("Manet a ouvert la porte aux impressionnistes, sans jamais exposer avec eux.",
                       "Le scandale du Déjeuner sur l'herbe, au Salon des refusés de 1863, fait de Manet le chef de file malgré lui de la jeune peinture. Monet, Renoir et Degas se retrouvent autour de lui au café Guerbois.",
                       "Le scandale du Déjeuner sur l'herbe, au Salon des refusés de 1863, puis celui de l'Olympia en 1865, font de Manet le chef de file malgré lui de la jeune peinture. Monet, Renoir, Degas et Bazille se retrouvent autour de lui au café Guerbois. Pourtant il refuse d'exposer avec eux en 1874 : il veut être reconnu au Salon officiel. L'été 1874, il peint quand même en plein air à Argenteuil, aux côtés de Monet, et sa palette s'éclaircit.")},
            {"type": "g", "work": "plum", "title": "La Prune",
             "stops": [
                 {"crop": None, "cap": T("Manet, vers 1877. Une jeune femme seule au café.",
                                         "Elle n'a pas allumé sa cigarette ni touché à son verre : elle attend, perdue dans ses pensées.",
                                         "Elle n'a pas allumé sa cigarette ni touché à sa prune à l'eau-de-vie, servie avec une cuillère. Elle attend, accoudée, perdue dans ses pensées. Le café, lieu de la vie moderne et de la solitude urbaine, est un sujet que Degas et Manet partagent.")},
                 {"crop": "z1", "cap": T("Un visage rêveur, à peine modelé.",
                                         "Le visage est posé en quelques plans clairs, la bouche d'une seule touche rouge.",
                                         "Le visage est posé en quelques plans clairs, presque sans ombre ; la bouche est une seule touche rouge, les yeux deux taches sombres. Manet obtient l'expression avec un minimum de moyens.")},
                 {"crop": "z2", "cap": T("Le verre et sa prune.",
                                         "Le verre est fait de reflets blancs posés en dernier, d'un geste sûr.",
                                         "Le verre n'existe que par quelques reflets blancs posés en dernier, d'un geste sûr, et par la tache brune de la prune. Manet était aussi un immense peintre de natures mortes : un détail comme celui-ci est un petit tableau dans le tableau.")},
             ]},
            {"type": "back", "work": "plum", "title": "Retour au parcours principal",
             "text": T("On reprend avec Monet.", "On reprend avec Monet, qui a peint à côté de Manet à Argenteuil.", "On reprend avec Monet, qui a peint à côté de Manet à Argenteuil en 1874. Ce détour compte dans ce que l'appli apprend : vous remontez aux origines d'un mouvement.")},
        ],
    },
}
